version: '3'

services:
    jekyll:
        image: jekyll/jekyll:latest
        volumes:
            - ./jekyll:/srv/jekyll
            - ./docs:/srv/jekyll/_site
        command: >
            bash -c "jekyll build
            && jekyll serve --watch --force_polling"
        ports: 
            - "4000:4000"
        depends_on:
            - data_to_map
    data_to_map:
        build:
            context: .
            dockerfile: ./compose/local/data_to_map/Dockerfile
        image: data_to_map_image
        volumes:
            - ./data_to_map:/srv/data_to_map
            - ./jekyll:/srv/jekyll
        command: python -u data_to_map/map.py
