version: '3'

services:
    jekyll:
        image: jekyll/jekyll:latest
        volumes:
            - ./docs:/srv/jekyll
        command: >
            bash -c "jekyll serve --force_polling
                     && touch /srv/jekyll/index.markdown"
        ports: 
            - "4000:4000"
        depends_on:
            - data_to_map
        restart: "always"
    data_to_map:
        build:
            context: .
            dockerfile: ./compose/local/data_to_map/Dockerfile
        image: data_to_map_image
        volumes:
            - ./data_to_map:/srv/data_to_map
            - ./docs:/srv/docs
        command: python -u data_to_map/map.py
        restart: "always"
