version: '3'

services:
    jekyll:
        image: jekyll/jekyll:latest
        volumes:
            - ./jekyll:/srv/jekyll
        command: jekyll build
        ports: 
            - "4000:4000"
    data_to_map:
        image: python:3